name: 'Setup Podman'
description: 'Setup podman and buildah binaries'
inputs:
  podman:
    description: 'podman version'
    required: false
    default: '5.4.0'
  buildah:
    description: 'buildah version'
    required: false
    default: '1.30.0'
  arch:
    description: 'architecture'
    required: false
    default: 'amd64'
outputs:
  podman:
    description: 'podman version'
  buildah:
    description: 'buildah version'
  arch:
    description: 'architecture'
runs:
  using: 'node20'
  main: 'dist/index.js'
